apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: petclinic
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
  clusterIP: None
  selector:
    app: postgres
