apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-pvc  
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: petclinic
            - name: POSTGRES_USER
              value: petclinic              
            - name: POSTGRES_PASSWORD
              value: petclinic
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data/" 
              name: data-volume
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-1-96.eu-west-2.compute.internal
