apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: petclinic
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/Users/srikrishnapeddinti/Downloads/hcp/kubs/data"  # Replace with your actual path