apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64      
      containers:
        - name: petclinic
          image: srikp/images:petclinic-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: petclinic
            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-1-96.eu-west-2.compute.internal